# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "thunderbolt" "usbhid" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/vgarch-root";
      fsType = "xfs";
    };

  fileSystems."/home" =
    { device = "/dev/mapper/vgarch-home";
      fsType = "xfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/A722-94CC";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/home/mat/Projects" =
    { device = "/dev/disk/by-uuid/33da77b8-14dd-4faf-8195-44f2136d7d3d";
      fsType = "xfs";
    };


#  fileSystems."/home/mat/disk" =
#    { device = "/dev/disk/by-uuid/4199E7D700E7CFC9";
#      fsType = "ntfs3";
#      options = [ "fmask=0022" "dmask=0022" "rw" "nofail" ];
#    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/dd4f38b6-32f0-4b7e-bb1e-b3d46ae910d2"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
