$mainMod = ALT

bind = $mainMod SHIFT, Q, killactive

bind = $mainMod, Return, exec, kitty
#bind = $mainMod, N, exec, librewolf
bind = $mainMod, D, exec, rofi -show drun

bind = $mainMod SHIFT, SPACE, togglefloating
bindm = $mainMod, mouse:272, movewindow
bind = SUPER, L, exec, loginctl lock-session

bind = SUPER, V, exec, cliphist list | wofi --show dmenu | cliphist decode | wl-copy

# Multimedia
bindle = , XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bindle = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindl  = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindl  = , XF86AudioMicMute, exec,  wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle 

bindle = , XF86MonBrightnessUp, exec, swayosd-client --brightness raise
bindle = , XF86MonBrightnessDown, exec, swayosd-client --brightness lower

# Screenshot
bind = ,Print, exec, bash -c 'grim -g "$(slurp)" - | wl-copy'
bind = SHIFT, Print, exec, bash -c 'grim -t png - | wl-copy'
bindrl = CAPS, Caps_Lock, exec, swayosd-client --caps-lock

# Player
bindl = , XF86AudioPrev, exec, playerctl previous
bindl = , XF86AudioNext, exec, playerctl next
bindl = , XF86AudioPause, exec, playerctl play-pause
bindl = , XF86AudioPlay, exec, playerctl play-pause
bindl = SUPER SHIFT, P, exec, playerctl play-pause
bindl = SUPER SHIFT, L, exec, playerctl previous
bindl = SUPER SHIFT, M, exec, playerctl next

# Movement
bind = $mainMod, R, submap, resize

submap = resize

binde = , H, resizeactive, -20 0
binde = , L, resizeactive, 20 0
binde = , K, resizeactive, 0 -20
binde = , J, resizeactive, 0 20

bind = , escape, submap, reset
bind = , return, submap, reset

submap = reset

bind = $mainMod, H, movefocus, left
bind = $mainMod, J, movefocus, down
bind = $mainMod, K, movefocus, up
bind = $mainMod, L, movefocus, right
bind = $mainMod, F, changegroupactive, f
bind = $mainMod, B, changegroupactive, b

bind = $mainMod SHIFT, H, movewindoworgroup, left
bind = $mainMod SHIFT, J, movewindoworgroup, down
bind = $mainMod SHIFT, K, movewindoworgroup, up
bind = $mainMod SHIFT, L, movewindoworgroup, right
bind = $mainMod SHIFT, F, movegroupwindow, f
bind = $mainMod SHIFT, B, movegroupwindow, b

bind = $mainMod, W, togglegroup, tab
bind = $mainMod, semicolon, lockactivegroup, toggle

bindl = $mainMod, Tab, cyclenext, none
bindl = $mainMod SHIFT, Tab, cyclenext, prev

bind = $mainMod SHIFT, F, fullscreen, 0

# Workspace
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

bind = $mainMod SHIFT, 1, movetoworkspacesilent, 1
bind = $mainMod SHIFT, 2, movetoworkspacesilent, 2
bind = $mainMod SHIFT, 3, movetoworkspacesilent, 3
bind = $mainMod SHIFT, 4, movetoworkspacesilent, 4
bind = $mainMod SHIFT, 5, movetoworkspacesilent, 5
bind = $mainMod SHIFT, 6, movetoworkspacesilent, 6
bind = $mainMod SHIFT, 7, movetoworkspacesilent, 7
bind = $mainMod SHIFT, 8, movetoworkspacesilent, 8
bind = $mainMod SHIFT, 9, movetoworkspacesilent, 9
bind = $mainMod SHIFT, 0, movetoworkspacesilent, 10

bind = $mainMod CTRL SHIFT, h, movecurrentworkspacetomonitor, l
bind = $mainMod CTRL SHIFT, l, movecurrentworkspacetomonitor, r
