pragma Singleton
import QtQuick

QtObject {
    readonly property string rosewater: "#f2d5cf"
    readonly property string flamingo: "#eebebe"
    readonly property string pink: "#f4b8e4"
    readonly property string mauve: "#ca9ee6"
    readonly property string red: "#e78284"
    readonly property string maroon: "#ea999c"
    readonly property string peach: "#ef9f76"
    readonly property string yellow: "#e5c890"
    readonly property string green: "#a6d189"
    readonly property string teal: "#81c8be"
    readonly property string sky: "#99d1db"
    readonly property string sapphire: "#85c1dc"
    readonly property string blue: "#8caaee"
    readonly property string lavender: "#babbf1"
    readonly property string text: "#c6d0f5"
    readonly property string subtext1: "#b5bfe2"
    readonly property string subtext0: "#a5adce"
    readonly property string overlay2: "#949cbb"
    readonly property string overlay1: "#838ba7"
    readonly property string overlay0: "#737994"
    readonly property string surface2: "#626880"
    readonly property string surface1: "#51576d"
    readonly property string surface0: "#414559"
    readonly property string base: "#303446"
    readonly property string mantle: "#292c3c"
    readonly property string crust: "#232634"
}
