pragma Singleton
import QtQuick

QtObject {
    readonly property string rosewater: "#dc8a78"
    readonly property string flamingo: "#dd7878"
    readonly property string pink: "#ea76cb"
    readonly property string mauve: "#8839ef"
    readonly property string red: "#d20f39"
    readonly property string maroon: "#e64553"
    readonly property string peach: "#fe640b"
    readonly property string yellow: "#df8e1d"
    readonly property string green: "#40a02b"
    readonly property string teal: "#179299"
    readonly property string sky: "#04a5e5"
    readonly property string sapphire: "#209fb5"
    readonly property string blue: "#1e66f5"
    readonly property string lavender: "#7287fd"
    readonly property string text: "#4c4f69"
    readonly property string subtext1: "#5c5f77"
    readonly property string subtext0: "#6c6f85"
    readonly property string overlay2: "#7c7f93"
    readonly property string overlay1: "#8c8fa1"
    readonly property string overlay0: "#9ca0b0"
    readonly property string surface2: "#acb0be"
    readonly property string surface1: "#bcc0cc"
    readonly property string surface0: "#ccd0da"
    readonly property string base: "#eff1f5"
    readonly property string mantle: "#e6e9ef"
    readonly property string crust: "#dce0e8"
}
